# Generated by Django 5.0.1 on 2024-03-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('gpa', models.FloatField()),
                ('age', models.IntegerField()),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='College.course')),
            ],
        ),
    ]
